### ISSUE TITLE
Bug for search_url variable

### ISSUE THREAD

**Issue by gotbletu** [Hoboneer/surfraw-tools#17]
```
$ mkelvis askubuntu 'www.askubuntu.com' 'https://askubuntu.com/search?q='

$ sr -p askubuntu firefox
https://https://askubuntu.com/search?q=firefox
```

seems like it adds the extra **https://** to the prefix of the **search_url** variable when it generates the script

**Comment by Hoboneer** [comment]
Hi, thanks for the issue.

The behaviour your describe isn't a bug, though it might be prudent to change it.   It's primarily to allow less typing and defaults to https.  `--insecure` changes the protocol to http.

**Comment by gotbletu** [comment]
i see

```
so instead of this
$ mkelvis askubuntu 'www.askubuntu.com' 'https://askubuntu.com/search?q='

i got to use this
$ mkelvis askubuntu 'www.askubuntu.com' 'askubuntu.com/search?q='

and if i want to use http instead of https
$ mkelvis askubuntu 'www.askubuntu.com' 'askubuntu.com/search?q=' --insecure
```

that seems like more work then just letting the user type it out on the commandline as is =)
most of the time they are gonna copy it from their web browser url anyways

Still good tho, saves me a bit of time. Thanks for the program

**Comment by Hoboneer** [comment]
> that seems like more work then just letting the user type it out on the commandline as is =)
most of the time they are gonna copy it from their web browser url anyways

This was an early design decision.  Appears to be a whoopsy, though it doesn't affect me too much since I don't really use `mkelvis` on the command line directly.

This behaviour might be changed in a future release if it turns out to be more trouble that it's worth.

**Comment by Hoboneer** [comment]
Hi, I've added this feature to `mkelvis` in commit 3f96bb1ca11ee1d80e4114be1d095002c17077ad.  URLs *with* or *without* URL schemes are accepted, but they must be the same.

I'll make a release including this feature (among others) soon.

**Comment by Hoboneer** [comment]
Hi, it took a while but I've made a [new release](https://pypi.org/project/surfraw-tools/) with this feature among others.  I also made some documentation at https://hoboneer.github.io/surfraw-tools/.  The changelog is [here](https://hoboneer.github.io/surfraw-tools/changelog/).

PS, I help maintain surfraw and we plan to complete a new release of surfraw over the next few weeks.  Elvis-specific completions should be part of it.
